name: release-new-version

on:
  push:
    branches: [ "master" ]

jobs:
  compile_and_release:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Typst
      run: |
        wget https://github.com/typst/typst/releases/latest/download/typst-x86_64-unknown-linux-musl.tar.xz
        tar -xf typst-x86_64-unknown-linux-musl.tar.xz
        sudo mv typst-x86_64-unknown-linux-musl/typst /usr/local/bin/
    
    - name: Compile Document
      run: |
        typst compile main.typ
        ls -al # List files to check if main.pdf exists

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v1.1.${{ github.run_number }}
        name: "Release v1.1.${{ github.run_number }}"
        generate_release_notes: true
        files: main.pdf
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload compiled document as release asset
      if: steps.create_release.outputs.upload_url != ''
      run: echo "âœ… main.pdf attached to release ${{ steps.create_release.outputs.upload_url }}"
